
INSERT INTO MK_USUARIO (ID, NOME,LOGIN, SENHA, EMAIL) VALUES (1,'CARLOS','CARLOSCCC','CARCAR','CAR@CAR');

ALTER SEQUENCE MK_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO MK_PERFIL (ID, DESCRICAO) VALUES (1,'ADMINISTRADOR');
INSERT INTO MK_PERFIL (ID, DESCRICAO) VALUES (2,'GERENTE');
INSERT INTO MK_PERFIL (ID, DESCRICAO) VALUES (3,'CLIENTE');

ALTER SEQUENCE MK_PERFIL_SEQ RESTART WITH 4;

INSERT INTO MK_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuário', 'usuario');
INSERT INTO MK_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO MK_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE MK_RECURSO_SEQ RESTART WITH 4;